services:
  postgres:
    image: postgres:15
    container_name: humanguard-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../backend/migrations:/docker-entrypoint-initdb.d:ro
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: humanguard-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - backend_network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: humanguard-keycloak
    restart: unless-stopped
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8081:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - backend_network

  backend:
    build: ../backend
    container_name: humanguard-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      - JWT_SECRET=${JWT_SECRET}
      - STORAGE_TYPE=${STORAGE_TYPE}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_USE_SSL=${MINIO_USE_SSL}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - FRONTEND_URL=${FRONTEND_URL}

      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - KEYCLOAK_REDIRECT_URL=${KEYCLOAK_REDIRECT_URL}
      - KEYCLOAK_REDIRECT_AUTH_URL=${KEYCLOAK_REDIRECT_AUTH_URL}
      - KEYCLOAK_TOKEN_URL=${KEYCLOAK_TOKEN_URL}
      - KEYCLOAK_INFO_URL=${KEYCLOAK_INFO_URL}

      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OAUTH_GOOGLE_REDIRECT_URL=${OAUTH_GOOGLE_REDIRECT_URL}

      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - OAUTH_GITHUB_REDIRECT_URL=${OAUTH_GITHUB_REDIRECT_URL}

    ports:
      - "8080:8080"
    networks:
      - backend_network
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ../frontend
    restart: unless-stopped
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - "80:80"
    networks:
      - backend_network

volumes:
  pg_data:
  minio_data:
  keycloak_data:

networks:
  backend_network:
    driver: bridge
