DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS shares;
DROP TABLE IF EXISTS files;
DROP TABLE IF EXISTS blacklist;
DROP TABLE IF EXISTS sites;
DROP TABLE IF EXISTS users;
DROP EXTENSION IF EXISTS "uuid-ossp";